version: "3.9"
services:
  vue-app:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - reseau
  gestion-commandes:
    build: ./nodejs-microservice
    restart: always
    ports:
      - "3000:3000"
    networks:
      - reseau

networks:
  reseau: